version: '3.1'

services:

  database:
    image: solopcloud/adempiere-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=adempiere
      - DB_NAME=adempiere
      - ADEMPIERE_PASSWORD=adempiere

  application:
    image: solopcloud/adempiere-base
    restart: always
    environment:
      - "ADEMPIERE_DB_HOST=database"
      - "ADEMPIERE_DB_NAME=adempiere"
      - "ADEMPIERE_DB_PASSWORD=adempiere"
      - "ADEMPIERE_DB_ADMIN_PASSWORD=adempiere"
    ports:
      - 8888:8888
